### ISSUE TITLE
Alternate CSS files not quite working?

### ISSUE THREAD

**Issue by tomchadwin** [regebro/impress-console#20] opened 2016-05-16 08:44 UTC
Do I use the alternate colour-scheme CSS files by specifying them with `.init(css="css/impressConsoleGray.css")`? When I do so (Chrome/Win7), the preview and next slide iframes are much smaller than they are with the default CSS. It's intermittent, but it's only once worked correctly, and fails every other time.

Default:

![default](https://cloud.githubusercontent.com/assets/7840213/15284654/805eedea-1b4a-11e6-94ca-a4b8e6f7f721.png)

Gray:

![gray](https://cloud.githubusercontent.com/assets/7840213/15284658/88cdfb7e-1b4a-11e6-89d2-be9cbe3bad68.png)

**Comment by bkueppers** [comment] 2016-09-23 12:05
Resizing the Browser works around that issue

**Comment by regebro** [comment] 2016-10-23 20:04
I can't reproduce this.

**Comment by norman-abramovitz** [comment] 2016-12-15 01:06
I am also having this issue.  I cannot tell if it is related the to errors when looking up viewslide div or not.  I also see this error with the default css.

**Comment by regebro** [comment] 2017-10-09 11:19
I still haven't seen this with default or non-default css. Closing for now.

**Closed by regebro** 2017-10-09 11:19 UTC
